# Generated by Django 3.0.2 on 2020-01-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200107_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='namggge',
            new_name='name',
        ),
    ]
